### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by brunano21** [michaelrhodes/peer-file#2]
Hello, 
I'd like to ask if this module is still in development.
Furthermore, could you provide a working example?
I'm try to transfer a file between to peer behind browser with no luck yet. 
Thanks in advance.

**Comment by michaelrhodes** [comment]
Hey, sorry for taking so long to get back to you. The module _is_ still in development, in that if issues come up, I'll patch them. But I'm not planning on adding any more features, if that’s what you meant.

I'll put together a legit example ASAP, but if you’re using browserify, you shouldn’t have to modify the README example too much.

**Comment by michaelrhodes** [comment]
I've made [a simple demo](http://michaelrhodes.github.io/peer-file/) whose source lives in [gh-pages/index.js](https://github.com/michaelrhodes/peer-file/blob/gh-pages/index.js).

Hope that helps! :)

**Comment by brunano21** [comment]
Yeah, thank you so much for you quick reply! However, I've worked hard and I was able to implement a working project which makes use of you library! It's really useful! 
A little suggestion - you should think if it could be useful: on the receive side, when .resume() or pause() are called, an event could be fired, like in the send side.
Finally, I opened another issue before this, because I had problem to understand how to use the library. This was due to the fact I did not know browserify, so at the beginning I need to figured out how it works :-) Maybe you could spend just two words for that.
Anyway, thanks!!
